extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_castle_wall_lights;
extern Lights1 castle_grounds_dl_castle_roof_lights;
extern u8 castle_grounds_dl_sand_vertex_i8[];
extern u8 castle_grounds_dl_grass_vertex_i8[];
extern u8 castle_grounds_dl_Texture0137_RGB_ci8[];
extern u8 castle_grounds_dl_Texture0137_RGB_pal_rgba16[];
extern u8 castle_grounds_dl_Texture0132_RGB_ci8[];
extern u8 castle_grounds_dl_Texture0132_RGB_pal_rgba16[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[31];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[319];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_2[30];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_3[18];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_3[];
extern Gfx mat_castle_grounds_dl_sand_vertex[];
extern Gfx mat_revert_castle_grounds_dl_sand_vertex[];
extern Gfx mat_castle_grounds_dl_grass_vertex[];
extern Gfx mat_revert_castle_grounds_dl_grass_vertex[];
extern Gfx mat_castle_grounds_dl_castle_wall[];
extern Gfx mat_revert_castle_grounds_dl_castle_wall[];
extern Gfx mat_castle_grounds_dl_castle_roof[];
extern Gfx mat_revert_castle_grounds_dl_castle_roof[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
