extern const GeoLayout replenishbob_hud_geo[];
extern Lights1 replenishbob_hud_right_lights;
extern Lights1 replenishbob_hud_left_lights;
extern u8 replenishbob_hud_replenishbob_test_left_rgba16[];
extern u8 replenishbob_hud_replenishbob_test_right_rgba16[];
extern Vtx replenishbob_hud_Cube_mesh_layer_1_vtx_0[20];
extern Gfx replenishbob_hud_Cube_mesh_layer_1_tri_0[];
extern Vtx replenishbob_hud_Cube_mesh_layer_1_vtx_1[4];
extern Gfx replenishbob_hud_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_replenishbob_hud_right[];
extern Gfx mat_replenishbob_hud_left[];
extern Gfx replenishbob_hud_Cube_mesh_layer_1[];
